In [14]:
from libs.srenv import SREnv
from libs.tree import Tree

import numpy as np
import torch

In [15]:
lib = {
    '+': 2,
    '-': 2,
    '/': 2,
    '*': 2,
    'cos': 1,
    'sin': 1,
    'X0': 0,
    'X1': 0,
    'X2': 0,
    'C': 0
}

X = torch.randn([2, 5])
y = 2.2 - X[0] / 11 + 7 * torch.cos(X[1])

In [16]:
print(X)
print(y)

tensor([[-0.3613,  1.4771, -0.7759,  0.1463,  2.2290],
        [-0.4969, -0.1081, -0.2478, -2.1155, -0.6371]])
tensor([ 8.3864,  9.0249,  9.0568, -1.4404,  7.6243])


In [17]:
print(y.shape)

torch.Size([5])


In [18]:
env = SREnv(library=lib, data=X, target=y)

In [19]:
state = env.reset()
a = ['+', '-', 'C', '/', 'X0', 'C', '*', 'C', 'cos', 'X1']
done = False

for i in range(len(a)):
    action = a[i]
    state, reward, done = env.step(action)
    print(state)

print(reward)


['+', 'PAD', 'PAD']
['+', '-', 'PAD', 'PAD', 'PAD']
['+', '-', 'C', 'PAD', 'PAD']
['+', '-', 'C', '/', 'PAD', 'PAD', 'PAD']
['+', '-', 'C', '/', 'X0', 'PAD', 'PAD']
['+', '-', 'C', '/', 'X0', 'C', 'PAD']
['+', '-', 'C', '/', 'X0', 'C', '*', 'PAD', 'PAD']
['+', '-', 'C', '/', 'X0', 'C', '*', 'C', 'PAD']
['+', '-', 'C', '/', 'X0', 'C', '*', 'C', 'cos', 'PAD']
['+', '-', 'C', '/', 'X0', 'C', '*', 'C', 'cos', 'X1']
tensor(1.)


In [20]:
env.expression.optimized_constants

tensor([ 2.2000, 11.0003,  7.0000])