In [1]:
from libs.srenv import SREnv

import numpy as np
import torch

In [2]:
lib = {
    '+': 2,
    '-': 2,
    '/': 2,
    '*': 2,
    'cos': 1,
    'sin': 1,
    'X0': 0,
    'X1': 0,
    'X2': 0,
    'C': 0
}

X = torch.randn([2, 5])
y = 2.2 - X[0] / 11 + 7 * torch.cos(X[1])

In [3]:
print(X)
print(y)

tensor([[-0.4206,  0.6441, -0.9489,  1.8143,  0.9127],
        [-1.7255,  0.5691, -0.9963, -0.2612, -0.6548]])
tensor([1.1594, 8.0382, 6.0902, 8.7977, 7.6691])


In [4]:
print(y.shape)

torch.Size([5])


In [5]:
env = SREnv(library=lib, data=X, target=y)

In [6]:
state = env.reset()
a = ['+', '-', 'C', '/', 'X0', 'C', '*', 'C', 'cos', 'X1']
done = False

for i in range(len(a)):
    action = a[i]
    state, reward, done = env.step(action)
    print(state)

print(reward)


['+', 'PAD', 'PAD']
['+', '-', 'PAD', 'PAD', 'PAD']
['+', '-', 'C', 'PAD', 'PAD']
['+', '-', 'C', '/', 'PAD', 'PAD', 'PAD']
['+', '-', 'C', '/', 'X0', 'PAD', 'PAD']
['+', '-', 'C', '/', 'X0', 'C', 'PAD']
['+', '-', 'C', '/', 'X0', 'C', '*', 'PAD', 'PAD']
['+', '-', 'C', '/', 'X0', 'C', '*', 'C', 'PAD']
['+', '-', 'C', '/', 'X0', 'C', '*', 'C', 'cos', 'PAD']
['+', '-', 'C', '/', 'X0', 'C', '*', 'C', 'cos', 'X1']
tensor(1.)


In [7]:
env.expression.optimized_constants

tensor([ 2.2000, 10.9998,  7.0000])